export const LOAD_CATEGORIES = "LOAD_CATEGORIES"
export const SET_CATEGORIES = "SET_CATEGORIES"
export const LOAD_CATEGORIES_FAILED = "LOAD_CATEGORIES_FAILED"
export const SET_DEPARTMENTS = "SET_DEPARTMENTS"
export const LOAD_DEPARTMENTS = "LOAD_DEPARTMENTS"
export const LOAD_DEPARTMENTS_FAILED = "LOAD_DEPARTMENTS_FAILED"

export const SET_PRODUCTS = "SET_PRODUCTS"
export const SET_PAGINATION = "SET_PAGINATION"

export const LOAD_PRODUCTS = "LOAD_PRODUCTS"
export const LOAD_PRODUCTS_FAILED = "LOAD_PRODUCTS_FAILED"

export const LOAD_PRODUCTS_SEARCH = "LOAD_PRODUCTS_SEARCH"
export const LOAD_PRODUCTS_SEARCH_FAILED = "LOAD_PRODUCTS_SEARCH_FAILED"

export const LOAD_PAGINATION = "LOAD_PAGINATION"
